### PR TITLE
(Re)moved unnecessary less, scss and css files, redesigned app, fixed js.

### PR DESCRIPTION
**Pull request by lesander**
Things I've changed so far:
- Removed the less and scss files of font-awesome, since they aren't being used by the webapp.
- Moved .css files to the `css/` directory and .js files to the `js/` directory. 
- Removed the empty lines in `index.html`. 
- Added old versions of Internet Explorer support.
- Redesigned the webapp.
- Settings now get saved on the go, instead of a [ENTER] press being required to save the field's data.

### CODE REVIEW

**Comment by MickdeGraaf** [comment]
Hi lesander thanks for your contribution to the project! Your fork is not working on Mac in chrome and safari. Also firefoxOS does not work. On Mac the settings screen does not show up and can't be opened. On firefoxOS only the settings screen is shown but not the controls. 

Code cleanup is nice thanks for that!  Layout is nicer than the current one however we're probably going to redesign it soon anyway.

If you fix issues we can merge these changes into the project

**Comment by lesander** [comment]
Yeah, the code I wrote has been tested on iOS and chrome (webkit). That's why I made this pull request on the `master` branch, and not the `firefoxos` branch. If you want me to remove the redesign, just ask :) I'd love to help you / this project in the future.

**Comment by MickdeGraaf** [comment]
can you remove the redesign then? This should probably also fix issues with the settings screen.

I'm glad you want to help this project! Can we exchange email adreses so we can talk in dutch?

**Comment by lesander** [comment]
Sure, I'll remove the redesign. My email can be found at my GitHub profile page :stuck_out_tongue:

**Comment by lesander** [comment]
I'm almost done reverting the css styles..

**Comment by lesander** [comment]
There we go. All design tweaks have been removed. Merge?

**Comment by lesander** [comment]
@MickdeGraaf can you revert #5, merge this pull and then apply the changes of #5 to the newer script?

**Comment by lesander** [comment]
Okay, @MickdeGraaf. Now this pull can be merged safely. :smiley:

**Comment by lesander** [comment]
Alright, this pull has been merged into the`dev` branch.

**Pull request closed without merging**
